### ISSUE TITLE
StyleCI/SDK replaces StyleCI/Config

### ISSUE THREAD

**Issue by GrahamCampbell** [Soullivaneuh/styleci-fixers#1]
Introducing: https://github.com/StyleCI/SDK.

---

You can simply do:

``` php
(new Client)->fixers())
```

now, to get an array of our fixers with their details.

NB That's coming from https://api.styleci.io/fixers.

**Comment by GrahamCampbell** [comment]
You can simply do:

```
(new Client)->fixers())
```

now, to get an array of our fixers with their details.

NB That's coming from https://api.styleci.io/fixers.

**Comment by GrahamCampbell** [comment]
We also have `->presets()` and /presets on the API.

**Comment by soullivaneuh** [comment]
Thanks for the tip, I'll look at that ! :+1:
